// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: internal/intelligence/proto/intelligence.proto

package intelligencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExtractBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*ExtractRequest      `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractBatchRequest) Reset() {
	*x = ExtractBatchRequest{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractBatchRequest) ProtoMessage() {}

func (x *ExtractBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractBatchRequest.ProtoReflect.Descriptor instead.
func (*ExtractBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractBatchRequest) GetDocuments() []*ExtractRequest {
	if x != nil {
		return x.Documents
	}
	return nil
}

type ExtractBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*ExtractResponse     `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractBatchResponse) Reset() {
	*x = ExtractBatchResponse{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractBatchResponse) ProtoMessage() {}

func (x *ExtractBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractBatchResponse.ProtoReflect.Descriptor instead.
func (*ExtractBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *ExtractBatchResponse) GetDocuments() []*ExtractResponse {
	if x != nil {
		return x.Documents
	}
	return nil
}

type ExtractResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Title                  string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleConfidence        float32                `protobuf:"fixed32,2,opt,name=title_confidence,json=titleConfidence,proto3" json:"title_confidence,omitempty"`
	DocumentType           string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentTypeConfidence float32                `protobuf:"fixed32,4,opt,name=document_type_confidence,json=documentTypeConfidence,proto3" json:"document_type_confidence,omitempty"`
	Entities               []*Entity              `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtractResponse) GetTitleConfidence() float32 {
	if x != nil {
		return x.TitleConfidence
	}
	return 0
}

func (x *ExtractResponse) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *ExtractResponse) GetDocumentTypeConfidence() float32 {
	if x != nil {
		return x.DocumentTypeConfidence
	}
	return 0
}

func (x *ExtractResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_intelligence_proto_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_internal_intelligence_proto_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Entity) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_internal_intelligence_proto_intelligence_proto protoreflect.FileDescriptor

const file_internal_intelligence_proto_intelligence_proto_rawDesc = "" +
	"\n" +
	".internal/intelligence/proto/intelligence.proto\x12\fintelligence\"\x0f\n" +
	"\rHealthRequest\"&\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"$\n" +
	"\x0eExtractRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"Q\n" +
	"\x13ExtractBatchRequest\x12:\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1c.intelligence.ExtractRequestR\tdocuments\"S\n" +
	"\x14ExtractBatchResponse\x12;\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1d.intelligence.ExtractResponseR\tdocuments\"\xe3\x01\n" +
	"\x0fExtractResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12)\n" +
	"\x10title_confidence\x18\x02 \x01(\x02R\x0ftitleConfidence\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x128\n" +
	"\x18document_type_confidence\x18\x04 \x01(\x02R\x16documentTypeConfidence\x120\n" +
	"\bentities\x18\x05 \x03(\v2\x14.intelligence.EntityR\bentities\"R\n" +
	"\x06Entity\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence2\xf9\x01\n" +
	"\x13IntelligenceService\x12C\n" +
	"\x06Health\x12\x1b.intelligence.HealthRequest\x1a\x1c.intelligence.HealthResponse\x12F\n" +
	"\aExtract\x12\x1c.intelligence.ExtractRequest\x1a\x1d.intelligence.ExtractResponse\x12U\n" +
	"\fExtractBatch\x12!.intelligence.ExtractBatchRequest\x1a\".intelligence.ExtractBatchResponseB7Z5papertrail/internal/intelligence/proto;intelligencepbb\x06proto3"

var (
	file_internal_intelligence_proto_intelligence_proto_rawDescOnce sync.Once
	file_internal_intelligence_proto_intelligence_proto_rawDescData []byte
)

func file_internal_intelligence_proto_intelligence_proto_rawDescGZIP() []byte {
	file_internal_intelligence_proto_intelligence_proto_rawDescOnce.Do(func() {
		file_internal_intelligence_proto_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_intelligence_proto_intelligence_proto_rawDesc), len(file_internal_intelligence_proto_intelligence_proto_rawDesc)))
	})
	return file_internal_intelligence_proto_intelligence_proto_rawDescData
}

var file_internal_intelligence_proto_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_intelligence_proto_intelligence_proto_goTypes = []any{
	(*HealthRequest)(nil),        // 0: intelligence.HealthRequest
	(*HealthResponse)(nil),       // 1: intelligence.HealthResponse
	(*ExtractRequest)(nil),       // 2: intelligence.ExtractRequest
	(*ExtractBatchRequest)(nil),  // 3: intelligence.ExtractBatchRequest
	(*ExtractBatchResponse)(nil), // 4: intelligence.ExtractBatchResponse
	(*ExtractResponse)(nil),      // 5: intelligence.ExtractResponse
	(*Entity)(nil),               // 6: intelligence.Entity
}
var file_internal_intelligence_proto_intelligence_proto_depIdxs = []int32{
	2, // 0: intelligence.ExtractBatchRequest.documents:type_name -> intelligence.ExtractRequest
	5, // 1: intelligence.ExtractBatchResponse.documents:type_name -> intelligence.ExtractResponse
	6, // 2: intelligence.ExtractResponse.entities:type_name -> intelligence.Entity
	0, // 3: intelligence.IntelligenceService.Health:input_type -> intelligence.HealthRequest
	2, // 4: intelligence.IntelligenceService.Extract:input_type -> intelligence.ExtractRequest
	3, // 5: intelligence.IntelligenceService.ExtractBatch:input_type -> intelligence.ExtractBatchRequest
	1, // 6: intelligence.IntelligenceService.Health:output_type -> intelligence.HealthResponse
	5, // 7: intelligence.IntelligenceService.Extract:output_type -> intelligence.ExtractResponse
	4, // 8: intelligence.IntelligenceService.ExtractBatch:output_type -> intelligence.ExtractBatchResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_intelligence_proto_intelligence_proto_init() }
func file_internal_intelligence_proto_intelligence_proto_init() {
	if File_internal_intelligence_proto_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_intelligence_proto_intelligence_proto_rawDesc), len(file_internal_intelligence_proto_intelligence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_intelligence_proto_intelligence_proto_goTypes,
		DependencyIndexes: file_internal_intelligence_proto_intelligence_proto_depIdxs,
		MessageInfos:      file_internal_intelligence_proto_intelligence_proto_msgTypes,
	}.Build()
	File_internal_intelligence_proto_intelligence_proto = out.File
	file_internal_intelligence_proto_intelligence_proto_goTypes = nil
	file_internal_intelligence_proto_intelligence_proto_depIdxs = nil
}
