# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intelligence.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'intelligence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intelligence.proto\x12\x0cintelligence\"\x0f\n\rHealthRequest\"\x1f\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"\x1e\n\x0e\x45xtractRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"F\n\x13\x45xtractBatchRequest\x12/\n\tdocuments\x18\x01 \x03(\x0b\x32\x1c.intelligence.ExtractRequest\"H\n\x14\x45xtractBatchResponse\x12\x30\n\tdocuments\x18\x01 \x03(\x0b\x32\x1d.intelligence.ExtractResponse\"\x9b\x01\n\x0f\x45xtractResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x18\n\x10title_confidence\x18\x02 \x01(\x02\x12\x15\n\rdocument_type\x18\x03 \x01(\t\x12 \n\x18\x64ocument_type_confidence\x18\x04 \x01(\x02\x12&\n\x08\x65ntities\x18\x05 \x03(\x0b\x32\x14.intelligence.Entity\"9\n\x06\x45ntity\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"<\n\rEmbedResponse\x12+\n\nembeddings\x18\x01 \x03(\x0b\x32\x17.intelligence.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\xbb\x02\n\x13IntelligenceService\x12\x43\n\x06Health\x12\x1b.intelligence.HealthRequest\x1a\x1c.intelligence.HealthResponse\x12\x46\n\x07\x45xtract\x12\x1c.intelligence.ExtractRequest\x1a\x1d.intelligence.ExtractResponse\x12U\n\x0c\x45xtractBatch\x12!.intelligence.ExtractBatchRequest\x1a\".intelligence.ExtractBatchResponse\x12@\n\x05\x45mbed\x12\x1a.intelligence.EmbedRequest\x1a\x1b.intelligence.EmbedResponseB7Z5papertrail/internal/intelligence/proto;intelligencepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intelligence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5papertrail/internal/intelligence/proto;intelligencepb'
  _globals['_HEALTHREQUEST']._serialized_start=36
  _globals['_HEALTHREQUEST']._serialized_end=51
  _globals['_HEALTHRESPONSE']._serialized_start=53
  _globals['_HEALTHRESPONSE']._serialized_end=84
  _globals['_EXTRACTREQUEST']._serialized_start=86
  _globals['_EXTRACTREQUEST']._serialized_end=116
  _globals['_EXTRACTBATCHREQUEST']._serialized_start=118
  _globals['_EXTRACTBATCHREQUEST']._serialized_end=188
  _globals['_EXTRACTBATCHRESPONSE']._serialized_start=190
  _globals['_EXTRACTBATCHRESPONSE']._serialized_end=262
  _globals['_EXTRACTRESPONSE']._serialized_start=265
  _globals['_EXTRACTRESPONSE']._serialized_end=420
  _globals['_ENTITY']._serialized_start=422
  _globals['_ENTITY']._serialized_end=479
  _globals['_EMBEDREQUEST']._serialized_start=481
  _globals['_EMBEDREQUEST']._serialized_end=510
  _globals['_EMBEDRESPONSE']._serialized_start=512
  _globals['_EMBEDRESPONSE']._serialized_end=572
  _globals['_EMBEDDING']._serialized_start=574
  _globals['_EMBEDDING']._serialized_end=601
  _globals['_INTELLIGENCESERVICE']._serialized_start=604
  _globals['_INTELLIGENCESERVICE']._serialized_end=919
# @@protoc_insertion_point(module_scope)
